"""Canonical Agent IR v0.1 data model."""

from .effects import CapabilityRule, CapabilitySet, Effect, EffectKind
from .errors import AIRModelError, DuplicateIdError, InvalidIdentifierError, SerializationError
from .ids import ActorRef, OpId, ProgramId, ResultId, ValueRef
from .operations import Operation, ResultDecl, SourceLocation
from .program import AIR_VERSION, Program
from .provenance import Provenance, TrustLabel, trust_transition_allowed
from .serde import (
    deserialize_program,
    operation_from_json_obj,
    operation_to_json_obj,
    program_from_json_obj,
    program_to_json_obj,
    serialize_program,
    serialize_program_bytes,
    value_to_json_obj,
)
from .types import (
    BOOL,
    BYTES,
    FLOAT,
    INT,
    JSON,
    STRING,
    TIMESTAMP,
    ListType,
    MapType,
    OptionalType,
    PrimitiveKind,
    PrimitiveType,
    RuntimeKind,
    RuntimeType,
    SemanticKind,
    SemanticType,
    TupleType,
    TypeDescriptor,
    parse_type,
)
from .values import (
    FrozenDict,
    JsonInput,
    JsonValue,
    Literal,
    Value,
    ValueInput,
    as_value,
    freeze_json,
    thaw_json,
)

__all__ = [
    "AIR_VERSION",
    "AIRModelError",
    "ActorRef",
    "BOOL",
    "BYTES",
    "CapabilityRule",
    "CapabilitySet",
    "DuplicateIdError",
    "Effect",
    "EffectKind",
    "FLOAT",
    "FrozenDict",
    "INT",
    "InvalidIdentifierError",
    "JSON",
    "JsonInput",
    "JsonValue",
    "ListType",
    "Literal",
    "MapType",
    "OpId",
    "Operation",
    "OptionalType",
    "PrimitiveKind",
    "PrimitiveType",
    "Program",
    "ProgramId",
    "Provenance",
    "ResultDecl",
    "ResultId",
    "RuntimeKind",
    "RuntimeType",
    "STRING",
    "SemanticKind",
    "SemanticType",
    "SerializationError",
    "SourceLocation",
    "TIMESTAMP",
    "TrustLabel",
    "TupleType",
    "TypeDescriptor",
    "Value",
    "ValueInput",
    "ValueRef",
    "as_value",
    "deserialize_program",
    "freeze_json",
    "operation_from_json_obj",
    "operation_to_json_obj",
    "parse_type",
    "program_from_json_obj",
    "program_to_json_obj",
    "serialize_program",
    "serialize_program_bytes",
    "thaw_json",
    "trust_transition_allowed",
    "value_to_json_obj",
]
